#!/usr/bin/env bash
# Regenerate THIRD_PARTY_NOTICES.md from the current go.sum.
# Runs inside the devcontainer (go-licenses is installed by post-create.sh).
#
# CI uses this script (the `licenses` job) to detect drift: if the regenerated
# file differs from the committed copy, the build fails.
#
# Usage:
#   bash scripts/gen-third-party-notices.sh         # writes THIRD_PARTY_NOTICES.md
#   bash scripts/gen-third-party-notices.sh check   # exits non-zero if out of date
set -euo pipefail

cd "$(dirname "$0")/.."

OUT=THIRD_PARTY_NOTICES.md
TMP=$(mktemp)
trap 'rm -f "$TMP" "$TMP.csv"' EXIT

if ! command -v go-licenses >/dev/null 2>&1; then
    echo "go-licenses not on PATH; install with: go install github.com/google/go-licenses@latest" >&2
    exit 2
fi

CSV="$TMP.csv"
# go-licenses 1.6.0 writes diagnostic noise to stderr (W0... warnings about
# stdlib packages); suppress it. CSV stays on stdout.
go-licenses csv ./... 2>/dev/null | sort -u > "$CSV"

{
    echo "# Third-Party Notices"
    echo
    echo "This file lists the third-party Go modules bundled with the postern binary"
    echo "and their licenses. Regenerated by \`make licenses\` from the current"
    echo "\`go.sum\` — do not edit by hand."
    echo
    echo "| Module | License | Source |"
    echo "|---|---|---|"
    while IFS=, read -r pkg url license; do
        [ -z "$pkg" ] && continue
        echo "| \`$pkg\` | $license | $url |"
    done < "$CSV"
    echo
    echo "## Original notices preserved verbatim"
    echo
    # Manual attributions live as markdown fragments under
    # scripts/manual-licenses/ — one file per upstream, sorted by name so the
    # rendered order is stable. Add a new entry by dropping a file in there
    # (the NN-name.md convention keeps the sort predictable).
    #
    # The directory must exist and contain at least one fragment: the
    # vendored tint and Infisical attributions are license requirements
    # (MIT). Silently rendering an empty section would ship a binary that
    # fails to honor its third-party attributions.
    shopt -s nullglob
    manual=(scripts/manual-licenses/*.md)
    shopt -u nullglob
    if [ ${#manual[@]} -eq 0 ]; then
        echo "scripts/manual-licenses/ is missing or empty; vendored attributions cannot be omitted" >&2
        exit 2
    fi
    for f in "${manual[@]}"; do
        cat "$f"
        echo
    done
} > "$TMP"

if [ "${1:-}" = "check" ]; then
    if ! diff -u "$OUT" "$TMP"; then
        echo "THIRD_PARTY_NOTICES.md is out of date; run 'make licenses' to regenerate." >&2
        exit 1
    fi
    echo "THIRD_PARTY_NOTICES.md is up to date."
else
    mv "$TMP" "$OUT"
    # mktemp output was renamed; trap rm will quietly skip.
    echo "wrote $OUT"
fi
