#!/usr/bin/env bash
# Regenerate THIRD_PARTY_NOTICES.md from the current go.sum.
# Runs inside the devcontainer (go-licenses is installed by post-create.sh).
#
# CI uses this script (the `licenses` job) to detect drift: if the regenerated
# file differs from the committed copy, the build fails.
#
# Usage:
#   bash scripts/gen-third-party-notices.sh         # writes THIRD_PARTY_NOTICES.md
#   bash scripts/gen-third-party-notices.sh check   # exits non-zero if out of date
set -euo pipefail

cd "$(dirname "$0")/.."

OUT=THIRD_PARTY_NOTICES.md
TMP=$(mktemp)
trap 'rm -f "$TMP" "$TMP.csv"' EXIT

if ! command -v go-licenses >/dev/null 2>&1; then
    echo "go-licenses not on PATH; install with: go install github.com/google/go-licenses@latest" >&2
    exit 2
fi

CSV="$TMP.csv"
# go-licenses 1.6.0 writes diagnostic noise to stderr (W0... warnings about
# stdlib packages); suppress it. CSV stays on stdout.
go-licenses csv ./... 2>/dev/null | sort -u > "$CSV"

{
    echo "# Third-Party Notices"
    echo
    echo "This file lists the third-party Go modules bundled with the postern binary"
    echo "and their licenses. Regenerated by \`make licenses\` from the current"
    echo "\`go.sum\` — do not edit by hand. PRD §13.8."
    echo
    echo "| Module | License | Source |"
    echo "|---|---|---|"
    while IFS=, read -r pkg url license; do
        [ -z "$pkg" ] && continue
        echo "| \`$pkg\` | $license | $url |"
    done < "$CSV"
    echo
    echo "## Original notices preserved verbatim"
    echo
    echo "### Infisical Agent Vault (MIT)"
    echo
    echo "Portions of this software are derived from Infisical Agent Vault"
    echo "(https://github.com/Infisical/agent-vault). The full MIT License text"
    echo "is reproduced below:"
    echo
    echo '```'
    echo "MIT License"
    echo
    echo "Copyright (c) 2022 Infisical Inc."
    echo
    echo "Permission is hereby granted, free of charge, to any person obtaining a copy"
    echo "of this software and associated documentation files (the \"Software\"), to deal"
    echo "in the Software without restriction, including without limitation the rights"
    echo "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell"
    echo "copies of the Software, and to permit persons to whom the Software is"
    echo "furnished to do so, subject to the following conditions:"
    echo
    echo "The above copyright notice and this permission notice shall be included in all"
    echo "copies or substantial portions of the Software."
    echo
    echo "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR"
    echo "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,"
    echo "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE"
    echo "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER"
    echo "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,"
    echo "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE"
    echo "SOFTWARE."
    echo '```'
} > "$TMP"

if [ "${1:-}" = "check" ]; then
    if ! diff -u "$OUT" "$TMP"; then
        echo "THIRD_PARTY_NOTICES.md is out of date; run 'make licenses' to regenerate." >&2
        exit 1
    fi
    echo "THIRD_PARTY_NOTICES.md is up to date."
else
    mv "$TMP" "$OUT"
    # mktemp output was renamed; trap rm will quietly skip.
    echo "wrote $OUT"
fi
